/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef auth_CONSTANTS_H
#define auth_CONSTANTS_H

#include "auth_types.h"

namespace coconut { namespace v1 {

class authConstants {
 public:
  authConstants();

  std::string ROLE_ADMINISTRATOR;
  std::string ROLE_ROOT;
  std::string UNKNOW_IP;
};

extern const authConstants g_auth_constants;

}} // namespace

#endif
