/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WechatOauth2_H
#define WechatOauth2_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "wechat_oauth2_types.h"

namespace coconut { namespace v1 {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class WechatOauth2If {
 public:
  virtual ~WechatOauth2If() {}
};

class WechatOauth2IfFactory {
 public:
  typedef WechatOauth2If Handler;

  virtual ~WechatOauth2IfFactory() {}

  virtual WechatOauth2If* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(WechatOauth2If* /* handler */) = 0;
  };

class WechatOauth2IfSingletonFactory : virtual public WechatOauth2IfFactory {
 public:
  WechatOauth2IfSingletonFactory(const ::std::shared_ptr<WechatOauth2If>& iface) : iface_(iface) {}
  virtual ~WechatOauth2IfSingletonFactory() {}

  virtual WechatOauth2If* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(WechatOauth2If* /* handler */) override {}

 protected:
  ::std::shared_ptr<WechatOauth2If> iface_;
};

class WechatOauth2Null : virtual public WechatOauth2If {
 public:
  virtual ~WechatOauth2Null() {}
};

class WechatOauth2Client : virtual public WechatOauth2If {
 public:
  WechatOauth2Client(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  WechatOauth2Client(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class WechatOauth2Processor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<WechatOauth2If> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (WechatOauth2Processor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
 public:
  WechatOauth2Processor(::std::shared_ptr<WechatOauth2If> iface) :
    iface_(iface) {
  }

  virtual ~WechatOauth2Processor() {}
};

class WechatOauth2ProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  WechatOauth2ProcessorFactory(const ::std::shared_ptr< WechatOauth2IfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< WechatOauth2IfFactory > handlerFactory_;
};

class WechatOauth2Multiface : virtual public WechatOauth2If {
 public:
  WechatOauth2Multiface(std::vector<std::shared_ptr<WechatOauth2If> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~WechatOauth2Multiface() {}
 protected:
  std::vector<std::shared_ptr<WechatOauth2If> > ifaces_;
  WechatOauth2Multiface() {}
  void add(::std::shared_ptr<WechatOauth2If> iface) {
    ifaces_.push_back(iface);
  }
 public:
};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class WechatOauth2ConcurrentClient : virtual public WechatOauth2If {
 public:
  WechatOauth2ConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  WechatOauth2ConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
