/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "auth_constants.h"

namespace coconut { namespace v1 {

const authConstants g_auth_constants;

authConstants::authConstants() {
  ROLE_ADMINISTRATOR = "administrator";

  ROLE_ROOT = "root";

  UNKNOW_IP = "n/a";

}

}} // namespace

