/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.saturn_xiv.coconut.v1;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class authConstants {

  public static final java.lang.String ROLE_ADMINISTRATOR = "administrator";

  public static final java.lang.String ROLE_ROOT = "root";

  public static final java.lang.String UNKNOW_IP = "n/a";

}
