/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.saturn_xiv.coconut.v1;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2024-01-17")
public enum LogLevel implements org.apache.thrift.TEnum {
  DEBUG(1),
  INFO(2),
  WARNING(3),
  ERROR(4);

  private final int value;

  private LogLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static LogLevel findByValue(int value) { 
    switch (value) {
      case 1:
        return DEBUG;
      case 2:
        return INFO;
      case 3:
        return WARNING;
      case 4:
        return ERROR;
      default:
        return null;
    }
  }
}
