/**
 * Autogenerated by Thrift Compiler (0.19.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.saturn_xiv.coconut.v1;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.19.0)", date = "2024-01-17")
public enum UserSignInBy implements org.apache.thrift.TEnum {
  EMAIL(1),
  NICKNAME(2),
  PHONE(3),
  GOOGLE_OAUTH2(11),
  WECHAT_OAUTH2(12),
  WECHAT_MINI_PROGRAM(13),
  FACEBOOK_OAUTH2(14);

  private final int value;

  private UserSignInBy(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static UserSignInBy findByValue(int value) { 
    switch (value) {
      case 1:
        return EMAIL;
      case 2:
        return NICKNAME;
      case 3:
        return PHONE;
      case 11:
        return GOOGLE_OAUTH2;
      case 12:
        return WECHAT_OAUTH2;
      case 13:
        return WECHAT_MINI_PROGRAM;
      case 14:
        return FACEBOOK_OAUTH2;
      default:
        return null;
    }
  }
}
